services:
  whatsapp:
    image: devlikeapro/waha
    restart : always
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./.sessions:/app/.sessions
      - .env:/app/.env 
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    env_file:
      - .env
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files
volumes:
  n8n_data: